# Reference: https://squidfunk.github.io/mkdocs-material/reference/
site_name: SANS HHC Write-Up
site_author: Insert Author name
theme:
  icon:
    # Material for MkDocs bundles several icon sets:
    # - Material Design (https://materialdesignicons.com/)
    # - FontAwesome (https://fontawesome.com/search?m=free)
    # - Octicons (https://octicons.github.com/)
    # - Simple Icons (https://simpleicons.org/)
    # Below are some suitable logo examples: 
    # logo: fontawesome/regular/snowflake
    # logo: fontawesome/solid/sleigh
    # logo: fontawesome/solid/candy-cane
    logo: fontawesome/solid/tree
  name: material
  favicon: img/misc/favicon.ico
  features:
    - toc.integrate
    - content.code.copy
    - navigation.sections
    #- navigation.instant
    #- navigation.top
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.expand
    #- navigation.top
    #- navigation.prune
    #- toc.follow
  palette:
    # Material for MkDocs supports a light (default) and dark (slate) theme.
    # Each mode supports configurable primary and accent colors.
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    # Primary colors:
    # red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal,
    # green, light green, lime, yellow, amber, orange, deep orange, brown,
    # grey, blue grey, black, and white.
    # Accent colors:
    # red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal,
    # green, light green, lime, yellow, amber, orange, and deep orange.
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/<twitter_username>
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/<github_username>
      name: GitHub
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/<instagram_username>
      name: Instagram
extra_css:
  - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tablesort.js
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - footnotes
  - def_list
  - toc:
      permalink: ⚓︎
      toc_depth: 2
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
# The 'nav' section defines the content of the sidebar navigation.
- Welcome: 'index.md'
- Objectives:
  - Section 1:
    - Objective 1: 'objectives/o1.md'
  - Section 2:
    - Objective 2: 'objectives/o2.md'
    - Objective 3: 'objectives/o3.md'
  - Section 3:
    - Objective 4: 'objectives/o4.md'
    - Objective 5: 'objectives/o5.md'
- Extras:
  - Easter Eggs: 'easter_eggs.md'
